name: Interceptor To Middleware E2E Test

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the tests on'
        required: false
        default: 'main'
        type: string
  push:
    branches: main

jobs:
  test-imsharer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clone layer8
        uses: actions/checkout@v2
        with:
          repository: globe-and-citizen/layer8
          path: layer8
          ref: development

      - name: Run layer8 server
        run: |
          cd layer8
          make setup_and_run &
          for attempt in {1..20}; do sleep 2; if curl -s http://localhost:5001/ > /dev/null; then break; fi; done

      - name: Clone middleware
        uses: actions/checkout@v2
        with:
          repository: globe-and-citizen/layer8-middleware
          path: layer8-middleware
          ref: development

      - name: Build middleware
        run: |
          cd layer8-middleware
          make build
          mkdir ../layer8/sp_mocks/imsharer/backend/dist
          mv ./dist/middleware.json ../layer8/sp_mocks/imsharer/backend/dist/
        working-directory: ./layer8-middleware

      - name: Clone interceptor
        uses: actions/checkout@v2
        with:
          repository: globe-and-citizen/layer8-interceptor
          path: layer8-interceptor
          ref: development

      - name: Build interceptor
        run: |
          cd layer8-interceptor
          make build
          echo "LAYER8_PROXY_SCHEME=http" > .env
          echo "LAYER8_PROXY_DOMAIN=localhost" >> .env
          echo "LAYER8_PROXY_PORT=5001" >> .env
          mkdir ../layer8/sp_mocks/imsharer/frontend/dist
          mv ./dist/interceptor.json ../layer8/sp_mocks/imsharer/frontend/dist/

      - name: Run imsharer backend
        run: |
          cd layer8/sp_mocks/imsharer/backend
          sed -i "s/('layer8_middleware')/require('.\/dist\/middleware')/g" index.js
          node index.js &
          for attempt in {1..20}; do sleep 2; if curl -s http://localhost:6001/ > /dev/null; then break; fi; done

      - name: Run imsharer frontend
        run: |
          cd layer8/sp_mocks/imsharer/frontend
          sed -i "s/('layer8_interceptor')/require('.\/dist\/interceptor')/g" src/App.vue
          sed -i "s/('layer8_interceptor')/require('.\/dist\/interceptor')/g" src/views/HomeView.vue
          npm install
          npm run dev &
          for attempt in {1..20}; do sleep 2; if curl -s http://localhost:5173/ > /dev/null; then break; fi; done

      - name: Run cypress tests
        uses: cypress-io/github-action@v6
        with:
          wait-on: 'http://localhost:5173'
          record: true
          browser: chrome
